[tool.ruff]

# Same as Black.
line-length = 120

# Assume Python 3.8.
target-version = "py38"

[tool.black]
line-length = 120
target-version = ['py38']
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  migrations/  # exclude migrations
)
'''
